name: Test OPA 1 maven git Actions
on: push
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Publish package
        run: |
          echo mvn -B package --file CODIGO/OPA/SistemaEmisiones/core/FrameQ-core/pom.xml
          echo mvn -B package --file CODIGO/OPA/SistemaEmisiones/web/framework-web/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
