name: Test OPA 1 maven git Actions
on: push
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Maven version
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.6.3

      - name: Change DNS to Cloudflare
        run: /usr/bin/echo -e "nameserver 1.1.1.1\nnameserver 8.8.8.8" | sudo tee /etc/resolv.conf
        
      - name: Publish package
        run: mvn -B package --file CODIGO/OPA/SistemaEmisiones/core/FrameQ-core/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}
